version: "3"

services:
  webserver:
    build:
      context: .
      dockerfile: .dev/Dockerfile.webserver
      target: prod
      args:
        WS_HOST_PORT: ${WS_HOST_PORT}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: project-webserver-dev
    depends_on:
      - database
    ports:
      - ${WS_HOST_PORT}:80
      - 9000:9000
    environment:
      PMA_PORT: ${PMA_HOST_PORT}
      WS_HOST_PORT: ${WS_HOST_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  database:
    # image: mysql:8.0
    build:
      context: .
      dockerfile: .dev/Dockerfile.database
      # args:
      #   REMOTE_SQL_FILE: ${REMOTE_SQL_FILE}
      #   LOCAL_SQL_FILE: ${LOCAL_SQL_FILE}
      #   MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: project-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_HOST_PORT}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project-phpmyadmin
    links:
      - database:db
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      # PMA_USER: ${MYSQL_USER}
      # PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${PMA_HOST_PORT}:80
